
logging:
  level:
    root: warn
    com.udemy: debug
  file:
    name: logs/debug.log
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbootad?user=root
    username: root
    password: kuanweitsai
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    mode: HTML

